// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortener.Infrastructure.Persistence;

#nullable disable

namespace UrlShortener.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortener.Domain.Entities.AccountEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("contactEmail");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.ToTable("account");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.DomainEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<long?>("AccountID")
                        .HasColumnType("bigint");

                    b.Property<string>("DefaultLink")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("defaultLink");

                    b.Property<string>("DomainURL")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("domainURL");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("system");

                    b.Property<long>("TotalShortenURL")
                        .HasColumnType("bigint")
                        .HasColumnName("totalShortenURL");

                    b.HasKey("ID");

                    b.ToTable("domain");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.RequestEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("AgentSource")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("agentSource");

                    b.Property<string>("Browser")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("browser");

                    b.Property<string>("BrowserVersion")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("browserVersion");

                    b.Property<string>("ForwardIP")
                        .HasColumnType("varchar(18)")
                        .HasColumnName("forwardIP");

                    b.Property<string>("IP")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ip");

                    b.Property<string>("IPv6")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ipv6");

                    b.Property<bool?>("IsUnique")
                        .HasColumnType("boolean")
                        .HasColumnName("isUnique");

                    b.Property<string>("OS")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("os");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Platform")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("platform");

                    b.Property<string>("Port")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("port");

                    b.Property<string>("QueryString")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("queryString");

                    b.Property<string>("RawRequest")
                        .HasColumnType("text")
                        .HasColumnName("rawRequest");

                    b.Property<string>("Referrer")
                        .HasColumnType("text")
                        .HasColumnName("referrer");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("requestDate");

                    b.Property<long?>("RequestLocationID")
                        .HasColumnType("bigint")
                        .HasColumnName("requestLocationID");

                    b.Property<string>("RequestType")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("requestType");

                    b.Property<DateTime?>("RequestedDate")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("requestedDate");

                    b.Property<long?>("URLID")
                        .HasColumnType("bigint")
                        .HasColumnName("URLID");

                    b.HasKey("ID");

                    b.HasIndex("RequestLocationID")
                        .IsUnique();

                    b.HasIndex("URLID");

                    b.ToTable("request");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.RequestLocationEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("CityName")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("cityName");

                    b.Property<string>("ContinentCode")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("continentCode");

                    b.Property<string>("ContinentName")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("continentName");

                    b.Property<string>("CountryName")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("countryName");

                    b.Property<string>("HashCache")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("hashCache");

                    b.Property<string>("ISOCode")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ISOCode");

                    b.Property<string>("Latitude")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("latitude");

                    b.Property<string>("Longitude")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("longitude");

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar(25)")
                        .HasColumnName("postalCode");

                    b.Property<string>("Subdivision")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("subdivision");

                    b.HasKey("ID");

                    b.ToTable("requestLocation");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.TagEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("createdDate");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("lastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("lastModifiedDate");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.ToTable("tag");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.URLEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<int?>("AccountID")
                        .HasColumnType("int")
                        .HasColumnName("accountID");

                    b.Property<int?>("CampaignID")
                        .HasColumnType("int")
                        .HasColumnName("campaignID");

                    b.Property<int?>("ClientID")
                        .HasColumnType("int")
                        .HasColumnName("clientID");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("createdDate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DomainID")
                        .HasColumnType("int")
                        .HasColumnName("domainID");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("endDate");

                    b.Property<string>("FullURL")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fullURL");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("varchar(125)")
                        .HasColumnName("hash");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("lastModifiedBy");

                    b.Property<DateTime?>("LastModifiedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("lastModifiedDate");

                    b.Property<int?>("OwnerID")
                        .HasColumnType("int")
                        .HasColumnName("ownerID");

                    b.Property<string>("RedirectUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("redirectURL");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("startDate");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("DomainID");

                    b.ToTable("url");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CodeExpire")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("codeExpire");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("passwordHash");

                    b.HasKey("ID");

                    b.ToTable("user");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.RequestEntity", b =>
                {
                    b.HasOne("UrlShortener.Domain.Entities.RequestLocationEntity", "RequestLocation")
                        .WithOne("Request")
                        .HasForeignKey("UrlShortener.Domain.Entities.RequestEntity", "RequestLocationID");

                    b.HasOne("UrlShortener.Domain.Entities.URLEntity", "Url")
                        .WithMany()
                        .HasForeignKey("URLID");

                    b.Navigation("RequestLocation");

                    b.Navigation("Url");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.URLEntity", b =>
                {
                    b.HasOne("UrlShortener.Domain.Entities.AccountEntity", "Account")
                        .WithMany("Urls")
                        .HasForeignKey("AccountID");

                    b.HasOne("UrlShortener.Domain.Entities.DomainEntity", "Domain")
                        .WithMany("Urls")
                        .HasForeignKey("DomainID");

                    b.Navigation("Account");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.AccountEntity", b =>
                {
                    b.Navigation("Urls");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.DomainEntity", b =>
                {
                    b.Navigation("Urls");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.RequestLocationEntity", b =>
                {
                    b.Navigation("Request")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
